BMECars.Web/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BMECars.Dal;
using BMECars.Dal.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BMECars.Web.Controllers
{
    public class CarsController : Controller
    {
        BMECarsDbContext _context;
        public CarsController(BMECarsDbContext bmeCarsDbContext)
        {
            _context = bmeCarsDbContext;
        }
        public async Task<IActionResult> Remove(int id)
        {
            var reservationsToDelete = await _context.Reservations.Where(r => r.CarId == id).ToListAsync();
            foreach(Reservation r in reservationsToDelete)
            {
                _context.Reservations.Remove(r);
            }
            Car car = await _context.Cars.Where(c => c.Id == id).FirstOrDefaultAsync();
            if(car != null)
                _context.Cars.Remove(car);

            await _context.SaveChangesAsync();
            return Ok(id);
        }
    }
}

BMECars.Web/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BMECars.Dal.DTOs;
using BMECars.Dal.Entities;
using BMECars.Dal.Managers;
using Microsoft.AspNetCore.Mvc;

namespace BMECars.Web.Controllers
{
    public class ReservationsController : Controller
    {
        public IReservationManager reservationManager;
        public ILocationManager locationManager;
        public ReservationsController(
            IReservationManager _reservationManager,
            ILocationManager _locationManager)
        {
            reservationManager = _reservationManager;
            locationManager = _locationManager;
        }
        

        [HttpGet("reservations/ApproveReservation/{id}")]
        public async Task<IActionResult> ApproveReservation(int id, bool approve = false)
        {
            await reservationManager.ApproveReservation(id, approve);
            return Redirect("/Index");
        }
    }
}

BMECars.Web/Pages/AddCar.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BMECars.Dal.DTOs;
using BMECars.Dal.Entities;
using BMECars.Dal.Managers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BMECars.Web.Pages
{
    public class AddCarModel : PageModel
    {
        public IEnumerable<SelectListItem> CompaniesForUser { get; set; }
        public IEnumerable<SelectListItem> AllCarBrandList { get; set; }
        public IEnumerable<SelectListItem> AvailableCategories { get; set; }
        public IEnumerable<SelectListItem> AllCountries { get; set; }

        [BindProperty]
        public InputCar InputCar { get; set; }
        [BindProperty]
        public IFormFile ImageOfCar { get; set; }


        ICarManager carManager;
        ICompanyManager companyManager;
        UserManager<User> userManager;
        ILocationManager locationManager;

        private IHostingEnvironment environment;

        public AddCarModel(
            ICarManager _carManager, 
            UserManager<User> _userManager, 
            ICompanyManager _companyManager,
            ILocationManager _locationManager,
            IHostingEnvironment _environment)
        {
            carManager = _carManager;
            userManager = _userManager;
            companyManager = _companyManager;
            locationManager = _locationManager;
            environment = _environment;
        }

        public async Task OnGet() {
            User user = await userManager.GetUserAsync(HttpContext.User);
            CompaniesForUser = companyManager.GetCompaniesForUser(user.Id).Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });

            AllCarBrandList = (await carManager.GetAllCarBrands()).Select(b => new SelectListItem {
                Text = b,
                Value = b
            });

            AvailableCategories = Enum.GetValues(typeof(Category)).OfType<Category>().ToList().Select(c => new SelectListItem {
                Text = c.ToString(),
                Value = c.ToString()
            });
            
            AllCountries = locationManager.GetAllCountries().Select(c => new SelectListItem
            {
                Text = c.ToString(),
                Value = c.ToString()
            });

        }

        public async Task<IActionResult> OnPostAsync(IList<CarInvidual> inviduals)
        {
            var file = Path.Combine("uploads", ImageOfCar.FileName);
            using (var fileStream = new FileStream(Path.Combine(environment.ContentRootPath, "wwwroot\\", file), FileMode.Create))
            {
                await ImageOfCar.CopyToAsync(fileStream);
            }

            foreach (CarInvidual ci in inviduals)
            {
                Console.WriteLine(ci.Plate);
            }
            if (ModelState.IsValid)
            {
                Company selectedCompany = await companyManager.GetCompany(InputCar.CompanyId);
                if(selectedCompany == null)
                {
                    ModelState.AddModelError("NoCompany", "Company not found.");
                    return Page();
                }
                foreach(CarInvidual ci in inviduals)
                {
                    await carManager.AddNewCarAsync(new Car
                    {
                        Brand = InputCar.Brand,
                        Price = (int)InputCar.Price,
                        Image = file,
                        IsFuelFull = (bool)InputCar.IsFuelFull,
                        Seat = (int)InputCar.Seat,
                        Year = (int)InputCar.Year,
                        Door = (int)InputCar.Door,
                        Transmission = (Transmission)InputCar.Transmission,
                        Climate = (bool)InputCar.Climate,
                        Category = (Category)InputCar.Category,
                        Bag = (int)InputCar.Bag,
                        Company = selectedCompany,
                        Plate = ci.Plate,
                        PickUpLocation = new Location {
                            Country = ci.Country,
                            City = ci.City,
                            Address = ci.PickUp,
                            Company = selectedCompany,
                            IsGlobal = false
                        }
                    });
                }
                
                return RedirectToPage("/");
            }
            return Page();
        }
        public class CarInvidual
        {
            [Required(ErrorMessage = "'Plate' can't be empty.")]
            public string Plate { get; set; }

            [Required(ErrorMessage = "'Country' can't be empty.")]
            public string Country { get; set; }

            [Required(ErrorMessage = "'City' can't be empty.")]
            public string City { get; set; }

            [Required(ErrorMessage = "'Pick Up' can't be empty.")]
            public string PickUp { get; set; }
        }
    }
    
}

BMECars.Web/Pages/Cars.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BMECars.Dal.DTOs;
using BMECars.Dal.Managers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BMECars.Web.Pages
{
    public class CarsModel : PageModel
    {
        ICarManager _carManager;
        ICompanyManager _companyManager;
        public CarsModel(ICarManager CarManager, ICompanyManager CompanyManager)
        {
            _carManager = CarManager;
            _companyManager = CompanyManager;       
        }
        public CompanyHeaderDTO Company { get; set; }
        public List<CarDTO> Cars { get; set; }

        public Dictionary<int, ReservationInfoDTO> ReservationInfo = new Dictionary<int, ReservationInfoDTO>();

        public async Task OnGet(int companyId)
        {
            Cars = _carManager.GetCarsForCompany(companyId);
            Company = await _companyManager.GetCompanyHeader(companyId);

            foreach(var car in Cars)
            {
                ReservationInfo.Add(car.Id, _carManager.GetReservationInfoForCar(car.Id));
            }
        }
    }
}

BMECars.Web/Pages/Cars/AddCar.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BMECars.Dal.DTOs;
using BMECars.Dal.Entities;
using BMECars.Dal.Managers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BMECars.Web.Pages.Cars
{
    public class AddCarModel : PageModel
    {
        public IEnumerable<SelectListItem> CompaniesForUser { get; set; }
        public IEnumerable<SelectListItem> AllCarBrandList { get; set; }
        public IEnumerable<SelectListItem> AvailableCategories { get; set; }
        public IEnumerable<SelectListItem> AllCountries { get; set; }

        public IEnumerable<SelectListItem> Locations { get; set; }

        [BindProperty]
        public InputCar InputCar { get; set; }
        [BindProperty]
        public IFormFile ImageOfCar { get; set; }

        public int CompanyId { get; set; }

        ICarManager carManager;
        ICompanyManager companyManager;
        UserManager<User> userManager;
        ILocationManager locationManager;

        private IHostingEnvironment environment;

        public AddCarModel(
            ICarManager _carManager, 
            UserManager<User> _userManager, 
            ICompanyManager _companyManager,
            ILocationManager _locationManager,
            IHostingEnvironment _environment)
        {
            carManager = _carManager;
            userManager = _userManager;
            companyManager = _companyManager;
            locationManager = _locationManager;
            environment = _environment;
        }

        public async Task<IActionResult> OnGet(int? companyId) {
            if (companyId == null) return Redirect("/profile");
            CompanyId = (int)companyId;
            await setDropDowns();
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(IList<CarInvidual> inviduals)
        {
            var file = Path.Combine("uploads", ImageOfCar.FileName);

            using (var fileStream = new FileStream(Path.Combine(environment.ContentRootPath, "wwwroot\\", file), FileMode.Create))
            {
                await ImageOfCar.CopyToAsync(fileStream);
            }
            file = "/" + file;
            

            if (ModelState.IsValid)
            {
                Company selectedCompany = await companyManager.GetCompany(InputCar.CompanyId);
                if(selectedCompany == null)
                {
                    ModelState.AddModelError("NoCompany", "Company not found.");

                    await setDropDowns();
                    return Page();
                }
                foreach (CarInvidual ci in inviduals)
                {
                    await carManager.AddNewCarAsync(new Car
                    {
                        Brand = InputCar.Brand,
                        Price = (int)InputCar.Price,
                        Image = file,
                        IsFuelFull = (bool)InputCar.IsFuelFull,
                        Seat = (int)InputCar.Seat,
                        Year = (int)InputCar.Year,
                        Door = (int)InputCar.Door,
                        Transmission = (Transmission)InputCar.Transmission,
                        Climate = (bool)InputCar.Climate,
                        Category = (Category)InputCar.Category,
                        Bag = (int)InputCar.Bag,
                        Company = selectedCompany,
                        Plate = ci.Plate,
                        PickUpLocationId = InputCar.LocationId
                    });
                }
                
                return RedirectToPage("/");
            }
            await setDropDowns();
            return Page();
        }


        private async Task setDropDowns()
        {
            User user = await userManager.GetUserAsync(HttpContext.User);
            CompaniesForUser = companyManager.GetCompaniesForUser(user.Id).Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });

            AllCarBrandList = (await carManager.GetAllCarBrands()).Select(b => new SelectListItem
            {
                Text = b,
                Value = b
            });

            AvailableCategories = Enum.GetValues(typeof(Category)).OfType<Category>().ToList().Select(c => new SelectListItem
            {
                Text = c.ToString(),
                Value = c.ToString()
            });

            Locations = (await locationManager.GetAvaiableLocationsForCompany(CompanyId)).Select(c => new SelectListItem
            {
                Text = c.Country + ", " + c.City + ", " + c.Address,
                Value = c.Id.ToString()
            });
        }


        public class CarInvidual
        {
            [Required(ErrorMessage = "'Plate' can't be empty.")]
            public string Plate { get; set; }
        }
    }
    
}

BMECars.Web/Pages/Cars/Modify.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BMECars.Dal.DTOs;
using BMECars.Dal.Entities;
using BMECars.Dal.Managers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BMECars.Web.Pages.Cars
{
    public class ModifyModel : PageModel
    {
        public CarDTO Car { get; set; }

        [BindProperty]
        public InputCar InputCar { get; set; }
        [BindProperty]
        public IFormFile ImageOfCar { get; set; }
        

        public IEnumerable<SelectListItem> AllCarBrandList { get; set; }
        public IEnumerable<SelectListItem> AvailableCategories { get; set; }
        public IEnumerable<SelectListItem> Locations { get; set; }


        ICarManager carManager;
        ILocationManager locationManager;
        private IHostingEnvironment environment;

        public ModifyModel(
            ICarManager _carManager,
            ILocationManager _locationManager,
            IHostingEnvironment _environment
            )
        {
            carManager = _carManager;
            locationManager = _locationManager;
            environment = _environment;
        }

        public async Task<IActionResult> OnGet(int id)
        {
            await InitCar(id);
            if (Car == null)
            {
                return Redirect("/profile");
            }
            
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if(ImageOfCar != null)
            {
                var file = Path.Combine("uploads", ImageOfCar.FileName);

                using (var fileStream = new FileStream(Path.Combine(environment.ContentRootPath, "wwwroot\\", file), FileMode.Create))
                {
                    await ImageOfCar.CopyToAsync(fileStream);
                }
                file = "/" + file;

                InputCar.Image = file;
            }

            await InitCar((int)InputCar.Id);
            if (ModelState.IsValid)
            {
                await carManager.UpdateCar(Car.Id, InputCar);
                return Redirect("/companies/cars/" + InputCar.CompanyId);
            }
            return Page();
        }

        public async Task InitCar(int id)
        {
            Car = await carManager.GetCar(id);
            AllCarBrandList = (await carManager.GetAllCarBrands()).Select(b => new SelectListItem
            {
                Text = b,
                Value = b,
                Selected = (b == Car.Brand)
            });

            AvailableCategories = Enum.GetValues(typeof(Category)).OfType<Category>().ToList().Select(c => new SelectListItem
            {
                Text = c.ToString(),
                Value = c.ToString(),
                Selected = (c == Car.Category)
            });
            
            Locations = (await locationManager.GetAvaiableLocationsForCompany(Car.CompanyId)).Select(c => new SelectListItem
            {
                Text = c.Country + ", " + c.City + ", " + c.Address,
                Value = c.Id.ToString(),
                Selected = (c.Id == Car.PickUpLocationId)
            });


        }
    }
}

BMECars.Web/Pages/Cars/AddCar.cshtml
@page "{id:int?}"
@model BMECars.Web.Pages.Cars.AddCarModel
@using BMECars.Dal.DTOs
@using BMECars.Dal.Entities
@{
    ViewData["Title"] = "AddCar";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2 style="padding: 25px 0px;">Add New Cars</h2>
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-lg-6">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="InputCar.Brand">Brand</label>
                        <select asp-for="InputCar.Brand" asp-items="Model.AllCarBrandList" class="form-control"></select>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="InputCar.Price">Price</label>
                        <input asp-for="InputCar.Price" class="form-control">
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="InputCar.Category">Category</label>
                        <select asp-for="InputCar.Category" asp-items="Model.AvailableCategories" class="form-control"></select>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="InputCar.Seat">Seat</label>
                        <input asp-for="InputCar.Seat" type="number" min="2" class="form-control">
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="InputCar.Bag">Bags</label>
                        <input asp-for="InputCar.Bag" type="number" min="1" class="form-control" placeholder="Enter bags">
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="InputCar.Transmission">Transmission</label>
                        <select asp-for="InputCar.Transmission" class="form-control">
                            <option value="">All</option>
                            <option value="Automatic">Automatic</option>
                            <option value="Manual">Manual</option>
                        </select>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="InputCar.IsFuelFull">Gas</label>
                        <select asp-for="InputCar.IsFuelFull" class="form-control">
                            <option value="" selected>All</option>
                            <option value="true">Full</option>
                            <option value="false">Empty</option>
                        </select>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="InputCar.Year">Year</label>
                        <input asp-for="InputCar.Year" type="number" min="1990" max="2019" class="form-control" placeholder="Enter year">
                    </div>
                </div>
                <div class="col-6">
                    <div name="door" class="form-group">
                        <label asp-for="InputCar.Door">Door</label>
                        <input asp-for="InputCar.Door" type="number" min="2" class="form-control" id="door" placeholder="Enter doors">
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="InputCar.Climate">Climate</label>
                        <select asp-for="InputCar.Climate" class="form-control" id="climate">
                            <option value="">All</option>
                            <option value="true">Yes</option>
                            <option value="false">No</option>
                        </select>
                    </div>
                </div>

                <div class="col-12">
                    <label asp-for="InputCar.LocationId">Location</label>
                    <select asp-for="InputCar.LocationId" class="form-control" asp-items="Model.Locations"></select>
                </div>
                <div class="col-6">
                    <label for="customFile">Car Picture</label>
                    <div>
                        <input type="file" asp-for="ImageOfCar" required>
                    </div>
                </div>
                <input type="hidden" asp-for="InputCar.CompanyId" value="@Model.CompanyId" />
            </div>
        </div>
        <div class="col-lg-6">
            <h3>Plates</h3>
            <div id="plateContainer">
                <div class="form-inline py-3" style="position: relative;">
                    <span>1. Plate: </span>
                    <input type="text" class="form-control float-right" name="inviduals[0].Plate" style="position: absolute; right: 0;">
                </div>
            </div>

            <span class="btn btn-success" onclick="AddNewCarInvidualFields()">Add</span>
            <input type="submit" class="btn btn-success float-right" value="Submit" />
            <div class="clearfix"></div>
        </div>
    </div>


</form>

BMECars.Web/Pages/Cars/Payment.cshtml
@page "{id:int?}"
@model BMECars.Web.Pages.Cars.PaymentModel
@{
    ViewData["Title"] = "Payment";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2 class="py-3">Payment information</h2>

<form asp-controller="Reservations" asp-action="MakeReservation" method="post">
    <div class="row">
        <div class="col-8">
            <h4 class="py-2">Billing details</h4>

            <div class="form-group">
                <label for="exampleFormControlSelect1">Previous informations</label>
                <select class="form-control" name="BillingDataId" asp-items="Model.PreviousBillingDatas">
                    <option value="0" selected>Add new billing information</option>
                </select>
            </div>

            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label for="firstname">Firstname</label>
                        <input type="text" class="form-control" name="Firstname" placeholder="Firstname">
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="lastname">Lastname</label>
                        <input type="text" class="form-control" name="Lastname" placeholder="Lastname">
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label for="companyname">Company name</label>
                        <input type="text" class="form-control" name="Company" placeholder="Company name">
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label for="country">Country</label>
                        <input type="text" class="form-control" name="Country" placeholder="Country">
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" class="form-control" name="Address" placeholder="Address">
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label for="city">City</label>
                        <input type="text" class="form-control" name="City" placeholder="City">
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label for="state">State</label>
                        <input type="text" class="form-control" name="State" placeholder="State">
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label for="postal">ZIP/Postal</label>
                        <input type="text" class="form-control" name="Postal" placeholder="Postal">
                    </div>
                </div>
            </div>

        </div>
        <div class="col-4">
            <h4 class="py-2">Reservation Details</h4>
            <img style="width: 100%; height: auto;" src="@Model.Car.Image" alt="Alternate Text" />
            <h4>@Model.Car.Brand @Model.Car.Year</h4>
            <p>Plate:<span class="float-right">@Model.Car.Plate</span></p>
            <p>Price:<span class="float-right">@Model.Car.Price €</span></p>
            <p>Pick-up:<span class="float-right">@Model.ReserveFrom.ToString("yyyy-MM-dd")</span></p>
            <p>Release:<span class="float-right">@Model.ReserveTo.ToString("yyyy-MM-dd")</span></p>
            <p>Total:<span class="float-right">@Model.TotalPrice €</span></p>
        </div>
    </div>

    <input type="hidden" name="Id" value="@Model.Car.Id" />
    <input type="hidden" name="PickUpLocationId" value="@Model.PickUpLocationId" />
    <input type="hidden" name="DropDownLocationId" value="@Model.DropDownLocationId" />
    <input type="hidden" name="ReserveFrom" value="@Model.ReserveFrom" />
    <input type="hidden" name="ReserveTo" value="@Model.ReserveTo" />

    <input class="btn btn-success float-right" type="submit" value="Reserve" />
    <div class="clearfix"></div>


</form>

BMECars.Web/Pages/Cars/Remove.cshtml
@page "{id:int}"
@using BMECars.Dal.Entities
@model BMECars.Web.Pages.Cars.RemoveModel
@{
    ViewData["Title"] = "Remove";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1 class="text-center py-4">Are you sure want to remove car with plate <a href="/cars/modify/@Model.Car.Id">@Model.Car.Plate</a>?</h1>

<h3>The following reservations will be <span class="text-warning">DELETED</span>!</h3>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Reserve from</th>
                <th scope="col">Reserve to</th>
                <th scope="col">Drop Down Location</th>
                <th scope="col">Pick Up Location</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var reservation in Model.ReservationsForCar)
            {
                <tr>
                    <td>
                        @reservation.ReserveFrom.ToString("yyyy MM dd")
                    </td>
                    <td>
                        @reservation.ReserveTo.ToString("yyyy MM dd")
                    </td>
                    <td>
                        @reservation.PickUpLocation.Country, @reservation.PickUpLocation.City, @reservation.PickUpLocation.Address
                    </td>
                    <td>
                        @reservation.DropDownLocation.Country, @reservation.DropDownLocation.City, @reservation.DropDownLocation.Address
                    </td>
                    @{
                        var statusColor = "yellow"; //pending
                        if (reservation.Accepted == ReservationStatus.Accepted) { statusColor = "green"; }
                        if (reservation.Accepted == ReservationStatus.Declined) { statusColor = "red"; }
                    }
                    <td style="background: @statusColor">
                        @if (reservation.Accepted == ReservationStatus.Accepted)
                        {
                            <span>Accepted</span>
                        }
                        else if (reservation.Accepted == ReservationStatus.Pending)
                        {
                            <span>Pending</span>
                        }
                        else
                        {
                            <span>Declined</span>
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<a class="btn btn-danger" href="/companies/cars/@Model.Car.CompanyId">Back to cars</a>

<form class="d-inline" method="post">
    <input type="hidden" name="id" value="@Model.Car.Id" />
    <input class="btn btn-success float-right" type="submit" value="I understood, remove car!" />
</form>